filter:
  paths:
    - src/*
  excluded_paths: [ tests/* ]

checks:
  php: true

tools:
  external_code_coverage:
    timeout: 600
    runs: 3

build:
  environment:
    php:
      version: 8.1
      ini:
        xdebug.mode: coverage
  cache:
    directories:
      - node_modules
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - composer self-update --2
      - composer install --no-interaction
  tests:
    before:
      - mkdir storage
      - chmod -R 777 storage
    override:
      - command: phpcs-run
        use_website_config: false
      - command: php -n -dzend_extension=xdebug -dxdebug.mode=coverage ./vendor/bin/phpunit --coverage-clover=coverage-clover
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'