filter:
  excluded_paths: [ tests/* ]
checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
build:
  environment:
    php: '8.1'
  cache:
    directories:
      - node_modules
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - composer self-update --2
      - composer install --no-interaction
  tests:
    before:
      - mkdir storage
      - chmod -R 777 storage
    override:
      - command: vendor/bin/phpunit --coverage-clover=laravel-tests-coverage
        coverage:
          file: laravel-tests-coverage
          format: clover
