filter:
  excluded_paths: [ tests/* ]
checks:
  php: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
build:
  environment:
    php: '8.1'
  cache:
    directories:
      - node_modules
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - composer self-update --2
      - composer install --no-interaction
  tests:
    before:
      - mkdir storage
      - chmod -R 777 storage
    override:
      - command: phpcs-run --config phpcs.xml
        use_website_config: false
      - command: vendor/bin/phpunit --coverage-clover=laravel-tests-coverage
        coverage:
          file: laravel-tests-coverage
          format: clover
