filter:
  paths:
    - src/*
  excluded_paths:
    - tests/*

checks:
  php: true

build:
  environment:
    php:
      version: 8.1
      ini:
        xdebug.mode: coverage
  cache:
    directories:
      - vendor/
      - ~/.composer/cache/
      - ~/.composer
  dependencies:
    override:
      - composer install --no-interaction
    before:
      - composer self-update --2
  tests:
    before:
      - mkdir storage
      - chmod -R 777 storage
    override:
      - command: phpcs-run
        use_website_config: false
      - command: 'vendor/bin/phpunit --coverage-clover tests/logs/clover.xml'
        coverage:
          file: 'tests/logs/clover.xml'
          format: 'php-clover'
