dist: xenial
language: php

php:
  - 7.1
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor
branches:
  only:
    - master
    - stable
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit

