dist: xenial
language: php
env:
  global:
    - XDEBUG_MODE=coverage
php:
  - 7.3.24
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor
branches:
  only:
    - master
    - stable
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

