dist: precise
language: php
php:
  - 7.1
cache:
  directories:
    - node_modules
    - vendor
branches:
  only:
    - master
    - stable
before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit

